fix: Added container class on every section
Kamikazi-Deborah/group-one-web-project pull request #14
Opened 2024-06-04 14:35 UTC by VictorMugisha

2024-06-04 14:59 UTC, MikeManzi requested changes
The class seems to be working, but it needs to be added to the other pages as well.

2024-06-05 11:44 UTC, Kamikazi-Deborah approved these changes

2024-06-06 12:32 UTC, kelliaUmuhire approved these changes
Looks good!

2024-06-06 13:04 UTC, tuyishimehono approved these changes

2024-06-06 13:09 UTC, tpambrose approved these changes
Perfect perfect perfect

2024-06-06 13:12 UTC, Kamikazi-Deborah approved these changes

2024-06-06 13:19 UTC, MikeManzi approved these changes

2024-06-06 13:34 UTC, merged